# Travis config file to build spk package
# Adapted from https://github.com/torrentalle/spksrc/tree/gogs-build
# And https://github.com/jelmerj/spksrc

# Only build tags
if: tag IS present

# Matrix identical to `all-supported`
env:
  matrix:
    - SYNOARCH=arch-x64-6.1
    - SYNOARCH=arch-x64-5.2
    - SYNOARCH=arch-88f6281-6.1
    - SYNOARCH=arch-alpine-6.1
    - SYNOARCH=arch-armada370-6.1
    - SYNOARCH=arch-armada375-6.1
    - SYNOARCH=arch-armada38x-6.1
    - SYNOARCH=arch-armadaxp-6.1
    - SYNOARCH=arch-comcerto2k-6.1
    - SYNOARCH=arch-denverton-6.1
    - SYNOARCH=arch-evansport-6.1
    - SYNOARCH=arch-hi3535-6.1
    - SYNOARCH=arch-monaco-6.1
    - SYNOARCH=arch-qoriq-6.1
    - SYNOARCH=arch-rtd1296-6.1
    - SYNOARCH=arch-ppc853x-5.2
    - SYNOARCH=arch-ipq806x-1.1

notifications:
  email: false

# The "sudo: required" image is fastest
sudo: required
dist: trusty

# Output is too verbose for TravisCI, so we hide it
# Remove the ">/dev/null" part to debug!
# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.

script:
  - PKG=${TRAVIS_TAG%%-*}
  - docker build -t spksrc-node .
  - docker run -it -v `pwd`:/spksrc spksrc-node /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make $SYNOARCH>/dev/null"
  - ls packages/*.spk

services:
- docker

git:
  depth: 1

deploy:
  provider: releases
  api_key:
    secure: YzbeXSSUcvgHRcn3s+P9ISXzltwM7J9e4ya+qYZlUsAORP96WXqNGyRnIgZaNq+ZiBn/kFPiRlkI8u03gw3+LdSQ2R88O912OKQ5bTsE3Fe73DNo703pLJHHjmjBljeo5sObSB9dAfxDA4fvJC8sSfBhNBJF0ktenCN4CejP7nA9FRo7GrIHbyz1ye96AKdS9+GxQlUOWIPO7tyqlIfpexIYA8/I51ZTS1XWzGJQ0JpHvP796KDMIE04qJ7nr1S/0EEbwLD/vKf28rqqsrraL2thcqF9fZOofx1fY8lUQWSs8AyXDvr/NWD5cJSRDb022E4XIP/xzFvGT8DSPhhWshSt1LXbBtHPwW+bpsG8Zhbs9Ta4sCxERZAVjzUJOtbi8J8IDYX84PJgSdB0es0Np28iCWEZ+PSYog+R/k1jg8U7IkT7+bxFhVXPCLu46crKexKf0vvH0hDp8GtRPirf7e+KMMVaIYzMfnsWeHO+Nj1z/6tUkgYToS+Y2s1PpXTDW8oOwBoit6ko0CdKF/8JgTm9cgKRMc/QDPCoGfzkGAnvK4TVTdCTG4cDjcKpdtemlDZ83xSnqjoPo3LR1hKUE85geEPN/js7ZYqTfe4MwhAfGGykHkjzPxQ6LLYdzvDOOvM+kd2fdqzcZDJNq3NUCtaJ89eMRxzTjvBZJBl1Yk0=
  file_glob: true
  file: packages/*.spk
  skip_cleanup: true
  overwrite: true
  on:
tags: true
