# CircleCI config file to build node spk package

version: 2

# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t spksrc-build .
      - run:
          command: |
            PKG=${CIRCLE_BRANCH%%-*}
            docker run -it -v `pwd`:/spksrc spksrc-build /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && PARALLEL_MAKE=2 make all-supported"
      - run: ls -l packages/*.spk
      - run: sudo pip3 install githubrelease
      - run: githubrelease asset florianbehrens/spksrc upload $CIRCLE_TAG packages/*.spk

