# CircleCI config file to build spk package

version: 2

# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.

"-": &build
  machine:
    image: ubuntu-1604:201903-01
  steps:
    - checkout
    - run: docker build -t spksrc-node .
    - run: docker run -it -v `pwd`:/spksrc spksrc-node /bin/bash -c "cd /spksrc && make setup && cd spk/node && make $CIRCLE_JOB"
    - run: ls -l packages/*.spk

jobs:
  arch-x64-6.1:
    <<: *build
  arch-x64-5.2:
    <<: *build
  arch-88f6281-6.1:
    <<: *build
  arch-alpine-6.1:
    <<: *build
  arch-armada370-6.1:
    <<: *build
  arch-armada375-6.1:
    <<: *build
  arch-armada38x-6.1:
    <<: *build
  arch-armadaxp-6.1:
    <<: *build
  arch-comcerto2k-6.1:
    <<: *build
  arch-denverton-6.1:
    <<: *build
  arch-evansport-6.1:
    <<: *build
  arch-hi3535-6.1:
    <<: *build
  arch-monaco-6.1:
    <<: *build
  arch-qoriq-6.1:
    <<: *build
  arch-rtd1296-6.1:
    <<: *build
  arch-ppc853x-5.2:
    <<: *build
  arch-ipq806x-1.1:
    <<: *build
  
workflows:
  version: 2
  build:
    jobs:
      - arch-x64-6.1
      - arch-x64-5.2
      - arch-88f6281-6.1
      - arch-alpine-6.1
      - arch-armada370-6.1
      - arch-armada375-6.1
      - arch-armada38x-6.1
      - arch-armadaxp-6.1
      - arch-comcerto2k-6.1
      - arch-denverton-6.1
      - arch-evansport-6.1
      - arch-hi3535-6.1
      - arch-monaco-6.1
      - arch-qoriq-6.1
      - arch-rtd1296-6.1
      - arch-ppc853x-5.2
      - arch-ipq806x-1.1
